<tr>
	<td id='fun-pdt-details'>
		<table class='t100' cellspacing='0'>
			<tr>
				<td colspan='4' class='colorBg t-bold'>
					<span style='font-size: 14px; padding: 3px;'>PRODUCT DETAILS</span>
				</td>
			</tr>
			<tr>
				<td class='t-bold'>Select A Product</td>
				<td id='fun-pdt-cover'></td>
				<td id='fun-pdt-opt'></td>
				<td id='fun-pdt-deps'></td>
			</tr>
			<tr>
				<td class='t-bold' style='line-height: 22px;'>Product Cost</td>
				<td colspan='3' style='line-height: 22px;' id='fun-pdt-cost'></td>
			</tr>
			<tr>
				<td colspan='4' style='line-height: 24px;'>&nbsp;</td>
			</tr>
		</table>
	</td>
</tr>