<tr>
	<td id='fun-dep-details'>
		<table class='t100' cellspacing='0'>
			<tr>
				<td colspan='6' class='colorBg t-bold'>
					<span style='font-size: 14px;'>DEPENDANTS DETAILS</span>
				</td>
			</tr>
			<tr id='fun-dep-details-header-col'>
				<th>Firstname</th><th>Surname</th>
				<th>Date Of Birth</th><th>ID / Passport No</th>
				<th>Gender</th><th>Relationship</th>
			</tr>
		</table>
	</td>
</tr>
<tr><td>&nbsp;</td></tr>
<tr>
	<td id='fun-submit-but-ct'></td>
</tr>