<tr>
	<td id='fun-main-details'>
		<table class='t100' cellspacing='0'>
			<tr>
				<td colspan='4' class='colorBg t-bold'>
					<span style='font-size: 14px;'>MEMBER DETAILS</span>
				</td>
			</tr>
			<tr>
				<td class='t-bold'>Firstname(s)</td>
				<td><?php echo $this->mem->fname ?></td>
				<td class='t-bold'>Surname</td>
				<td><?php echo $this->mem->sname ?></td>
			</tr>
			<tr>
				<td class='t-bold'>ID / Passport Number</td>
				<td><?php echo $this->mem->id ?></td>
				<td class='t-bold'>Occupation</td>
				<td><?php echo $this->mem->work ?></td>
			</tr>
			<tr>
				<td colspan='4' style='line-height: 24px;'>&nbsp;</td>
			</tr>
		</table>
	</td>
</tr>